--- # unte execute chyyi with nodename ssd or else keep as pending
apiVersion: v1
kind: Pod
metadata:
  name: node-selector-demo
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always
  nodeSelector:
    disktype: 
