--- # so manam icchina match ayina node ki kakunda vere node ki velthayi pods.
apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity
  namespace: roboshop
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: hardware
            operator: NotIn
            values:
            - gpu
  containers:
  - name: with-node-affinity
    image: nginx