apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    app-name: pod-1
    purpose: pod-affinity
spec:
  containers:
  - name: pod-1
    image: nginx
---  # pod2 pod 1 daggariki vellali same node
